definitions:
  model.Question:
    properties:
      answer:
        type: string
      created_at:
        type: string
      id:
        type: integer
      text:
        type: string
      updated_at:
        type: string
      upvotes:
        type: integer
    type: object
  questionController.GetQuestionsSwagger:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Question'
        type: array
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/questions:
    get:
      consumes:
      - application/json
      description: get response questions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/questionController.GetQuestionsSwagger'
            type: array
      summary: questions response
      tags:
      - question
swagger: "2.0"
